### PR TITLE
Disable Match Path with exact: searches

### PR DESCRIPTION
**Pull request by mike406**
For issue https://github.com/lin-ycv/EverythingPowerToys/issues/117

### CODE REVIEW

**Comment by mike406** [comment]
Amended PR with commit [7978d45](https://github.com/lin-ycv/EverythingPowerToys/pull/120/commits/7978d4522f97ce3a711a77d9b43791d499f96bab) so that `MatchPath` isn't logged when an exact: search contains quotes,

**Comment by lin-ycv** [comment]
Nice catch. But I think I'd prefer to fix this by removing the feature where quotation marks sets path matching

cause according to everything docs, all of the following does the same thing:
```
wfn:
wholefilename:
nowfn:
nowholefilename:
exact:
```
And quotation marks can also use used to do exact search when using other modifiers

Or maybe something like ` :` sets patch matching, but `:”` doesn't. (Needs to also check how the affects when regex is enabled)

@mike406 your thoughts on this?

Ref: https://www.voidtools.com/support/everything/searching/

**Comment by mike406** [comment]
So it's tricky, if you enable Match Path in the plugin settings it creates the opposite issue, exact: matches without quotation marks will no longer show up. So maybe what we need to do is create an array of ["wfn:", "wholefilename:", "nowfn:", "nowholefilename:", "exact:"] and omit all of them from using Match Path.

**Comment by mike406** [comment]
My C# is not great but given the above findings with Match Path but something like this appears to work: https://github.com/lin-ycv/EverythingPowerToys/pull/120/commits/1c6296f584ab7756e8a02f12d755021b995dbe3d

**Comment by lin-ycv** [comment]
so after some testing, the easiest fix is to simply remove the feature where `"` triggers path matching
this feature wasn't even actually needed, everything already had a similar feature using `\`
image

**Pull request merged**
